// automatically generated by stateify.

//go:build linux
// +build linux

package stopfd

import (
	"context"

	"github.com/sagernet/gvisor/pkg/state"
)

func (sf *StopFD) StateTypeName() string {
	return "pkg/tcpip/link/stopfd.StopFD"
}

func (sf *StopFD) StateFields() []string {
	return []string{
		"EFD",
		"stopped",
	}
}

func (sf *StopFD) beforeSave() {}

// +checklocksignore
func (sf *StopFD) StateSave(stateSinkObject state.Sink) {
	sf.beforeSave()
	stateSinkObject.Save(0, &sf.EFD)
	stateSinkObject.Save(1, &sf.stopped)
}

func (sf *StopFD) afterLoad(context.Context) {}

// +checklocksignore
func (sf *StopFD) StateLoad(ctx context.Context, stateSourceObject state.Source) {
	stateSourceObject.Load(0, &sf.EFD)
	stateSourceObject.Load(1, &sf.stopped)
}

func init() {
	state.Register((*StopFD)(nil))
}
